---
default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: CHANGELOG.md
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
        exclude: /template/
    -   id: debug-statements
    -   id: name-tests-test
        args: [--django]
    -   id: requirements-txt-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
        exclude: ^paasta_tools/paastaapi
    -   id: pretty-format-json
        args: [
          '--autofix',
          '--indent', '4',
          '--no-sort-keys',
        ]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
        additional_dependencies: [aspy.refactor_imports==0.5.3]
        exclude: ^paasta_tools/paastaapi
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.12.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
        exclude: ^paasta_tools/paastaapi
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: ['--target-version', 'py310']
        exclude: ^paasta_tools/paastaapi
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: ['--ignore', 'E231,W503', '--max-line-length', '100']
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*tests/.*|.*yelp/testing/.*|\.pre-commit-config\.yaml
